### ISSUE TITLE
[Soft Question] Vectors in the basis: columns or rows

### ISSUE THREAD

**Issue by hilder-vitor** [kutio/liblll#3]
Hi!

The function lll_reduction receives a matrix n that represents the basis of the lattice. Does the code of this function assumes that the vectors of the basis are the rows or the columns of that matrix n?

For instance, if the basis has the following vectors:

b1 = (0, 10, -9)
b2 = (17, 0, 11)

then I have to pass

n= | 0, 10, -9  |
. .   | 17, 0, 11 |

or 

.  .  |  0     17  |
n= | 10    0   |
.  .  | -9     11 |

?

Thank you

**Comment by kutio** [comment]
Hello,

I think :

n = [ [ 0,  17], [10, 0], [-9, 11]]
n = create_matrix(n)
print_mat(n)

n_red = lll_reduction(n)
print_mat(n)

kutio

2017-02-03 13:41 GMT+01:00 Hilder Vitor Lima Pereira <
notifications@github.com>:

**Comment by hilder-vitor** [comment]
Thank you for answering. 
Please, take a look at my Pull-request.   (:
